name: "Auto Release Milestone"
description: "Drafts a GitHub release based on a newly created milestone"
author: "Jan Pfajfr"
outputs:
  release-url:
    description: "The URL of the GitHub release that was drafted"
runs:
  using: "docker"
  image: "Dockerfile"